---
- hosts: all
  become: true
  tasks:
    - name: Installing Packages in Ubuntu
      apt: 
        name: ["git","apache2"]
        state: present
      when: ansible_os_family == 'Debian'
    - name: Starting Apache in Ubuntu
      service: 
        name: apache2
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'
    - name: Installing Packages in AmazonLinux
      yum: 
        name: ["git","httpd"]
        state: present
      when: ansible_os_family == 'RedHat'
    - name: Starting Apache in AmazonLinux
      service: 
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == 'RedHat'
    - name: Coping Source
      copy: 
        src: ./index.html
        dest: /var/www/html/
